config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  get '/portfolio', to: 'pages#portfolio'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
  <!-- bootstrap start -->
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- bootstrap end -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
<div class="header">
  <div class="container">
    <div class="col-xs-8" id="menu">
    <ul>
      <li>Welcome</li>
      <li>Portfolio</li>
      <li>Blog</li>
      <li>About</li>
      <li>Contact</li>
    </ul>
    </div>
    <div class="col-xs-4">
      Jane Doe
    </div>
  </div>
</div>

<div class="main">
  <div class="jumbotron">
    <h2>Web developer.</h2>
    
    <%= link_to "View my work", portfolio_path, id: "work-btn", :class => "btn btn-lg right", role: "button" %>
  </div>
</div>

<div class="footer">
  <ul>
    <li><a href="#">GitHub </a></li>
    <li><a href="#">Twitter </a></li>
    <li><a href="#">LinkedIn</a></li>
    <li>2016 Jane Doe</li>
  </ul>
</div>